service: n7QandA
 
frameworkVersion: '2'
 
provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: ap-northeast-1
  timeout: 29 
 
custom:
  env: ${file(./config/env.yml)}
 
functions:
  parse:
    image: "${self:custom.env.accountID}.dkr.ecr.${self:custom.env.region}.amazonaws.com/\
      ${self:custom.env.repository}@${self:custom.env.digest}"