service: n7QandA
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.8
  region: ap-northeast-1
  timeout: 29
  iamRoleStatements: 
    - Effect: Allow 
      Action: 
        - s3:* 
      Resource:
        - "*"

functions:
  learn:
    image: 132681501358.dkr.ecr.ap-northeast-1.amazonaws.com/n7chat@sha256:51c0b69052570c1cf5464c9e592cb9d8d31c36209ed0b08b3263ca30dc7e6564
    events:
      - s3:
          bucket: putlambdan7chat
          event: s3:ObjectCreated:*
          rules:
            - prefix: text/
            - suffix: .txt
  chat:
    image: 132681501358.dkr.ecr.ap-northeast-1.amazonaws.com/n7chatchat@sha256:a11f5060f583c827792d93b1190ca38be22d28145906ce998605269aadf067d1
    events:
      - http:  	
          path: posts/create
          method: post
