service: n7QandA
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.8
  region: ap-northeast-1
  timeout: 29
  iamRoleStatements: 
    - Effect: Allow 
      Action: 
        - s3:* 
      Resource:
        - "*"

functions:
  parse:
    image: 132681501358.dkr.ecr.ap-northeast-1.amazonaws.com/n7chat@sha256:9b6065fdc7ae1a35620e41005f307f22b3b0b08be4a30f2c124189f63c4daf4e
    events:
      - s3:
          bucket: putlambdan7chat
          event: s3:ObjectCreated:*
          rules:
            - prefix: text/
            - suffix: .txt
