service: n7QandA
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.8
  region: ap-northeast-1
  timeout: 29
  iamRoleStatements: 
    - Effect: Allow 
      Action: 
        - s3:* 
      Resource:
        - "*"

functions:
  learn:
    image: 132681501358.dkr.ecr.ap-northeast-1.amazonaws.com/n7chat@sha256:4c1554afbeed7f6ded9a26549a82558b92836ae37f854f340f4e4487b78ebf28
    events:
      - http:  	
          path: posts/create
          method: post