service: n7QandA
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.8
  region: ap-northeast-1
  timeout: 29
  iamRoleStatements: 
    - Effect: Allow 
      Action: 
        - s3:* 
      Resource:
        - "*"

functions:
  parse:
    image: 132681501358.dkr.ecr.ap-northeast-1.amazonaws.com/n7chat@sha256:ec20469c29d3773c9239c22cb79e83c3a4d3c789f9c73828b19ddd5e76fba9c9
    events:
      - s3:
          bucket: putlambdan7chat
          event: s3:ObjectCreated:*
          rules:
            - prefix: text/
            - suffix: .txt
