service: n7QandA
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: ap-northeast-1
  timeout: 29
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogStream
        - logs:PutLogEvents
        - "s3:GetObject"
        - "s3:PutObject"
      Resource:
      	- "arn:aws:s3:::allow-s3-role/*"

functions:
  parse:
    image: 132681501358.dkr.ecr.ap-northeast-1.amazonaws.com/n7learn-container@sha256:4f89404b1c5cc846d609b76dbb859ee98391eb5d0d07f9aee869db39417ca7bd
